### ISSUE TITLE
Could not upload file

### ISSUE THREAD

**Issue by eMahtab** [flyingsparx/NodeDirectUploader#11] opened 2016-06-19 06:49 UTC
When I try to upload the file I get file can not be uploaded. I have set all the environment variables but still I get that error.

**Comment by willwebberley** [comment] 2016-06-20 09:17
@eMahtab Please can you provide a bit more context around your issue? In particular, the exact request that isn't working for you and the type of error being returned

**Comment by ChrisGrigg** [comment] 2016-06-22 06:12
You've setup a good example.

I'm getting the same issue with the following error on both Chrome and Firefox:

> XMLHttpRequest cannot load https://s3.amazonaws.com/nns.app.images/Nom%20Nom%20Snap.png?AWSAccessKeyId…=1466571088&Signature=9zyWWJrY5oQQtunDbZ1oRtVrJSo%3D&x-amz-acl=public-read. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://desolate-island-40106.herokuapp.com' is therefore not allowed access.

The "getSignedRequest()" method is successful but when it tries to upload a file under "uploadFile()" 'xhr.status' is '0'.

I tried adding CORS Header permissions to express but with no luck.

I uploaded your example to https://desolate-island-40106.herokuapp.com/account

Any ideas?

Thanks

**Comment by comebacknader** [comment] 2016-06-24 22:30
I'm getting the same problem with this output: 

`XMLHttpRequest cannot load https://s3.amazonaws.com/userphoto......[omitted for privacy reasons]........... Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://lvh.me:3000' is therefore not allowed access."`

I've also included all the necessary CORS Header permissions, and I've only tested on Safari and Chrome, but it still doesn't work.

**Comment by willwebberley** [comment] 2016-06-26 15:04
@ChrisGrigg The CORS setup needs to be completed on the S3 side. In particular, please see [this section](https://devcenter.heroku.com/articles/s3-upload-node#s3-setup) of the article that this repository is the companion to. I imagine it may be redundant, in this case, to setup CORS on the Express app itself? 

It may be worth having a read through the rest of the article as well just to make sure you've got everything covered! If that still doesn't work, then I suggest trying a few different files (e.g. ones without spaces in the name) just to see if it's a particular file/mimetype that's failing.

@comebacknader Likewise, have you made sure your S3 bucket is configured correctly with the appropriate CORS setup? (please see the link I included above). I can't tell from your message whether you mean app-side headers or headers setup for the actual bucket. The bucket needs to allow requests from at least your own domain.

**Comment by comebacknader** [comment] 2016-06-26 15:50
Thanks for responding, my mistake stemmed from omitting the region in the headers. Once I included it, everything worked with the CORS setup.

**Comment by ChrisGrigg** [comment] 2016-06-27 00:32
Thanks for the response. Turns out I had the same issue with the region, not quite sure why I needed it when you didn't. Anyway I added the code below to fix the issue:

`aws.config.region = 'ap-southeast-2';`

**Comment by suryatejaswi89** [comment] 2017-03-06 02:15
I dont get any error but my bucket is still empty after running this code

**Comment by willwebberley** [comment] 2017-03-07 22:35
@suryatejaswi89 Please try to provide a little more context with this to help me see what's going on. In particular, please check all requests complete successfully and check for any errors reported to the console.

**Comment by mostafa-drz** [comment] 2017-06-23 18:04
@flyingsparx 
Hi, I read your article on heroku website and I tried to implement it, But I got the error code 400(bad request), after searching a lot, I found out the problem is "we have to define the region in for aws".anyway my code is working now with this line:
aws.config.region="us-east-2"
I'm using google chrome.

For anybody else if has the same problem, here is the list of regions:
http://docs.aws.amazon.com/general/latest/gr/rande.html

**Comment by faridhajnal** [comment] 2017-08-03 19:54
Hello, just as a comment.
I've followed the Heroku article step-by-step and the thing that made the project not to work was actually the aws-sdk region, as @ChrisGrigg pointed ! Thanks a lot! And hopefully this instruction (changing the region accordingly) can be included for future developments trying the tutorial!

**Comment by willwebberley** [comment] 2017-08-05 10:11
Hey @faridhajnal - thanks for the comment. This has been a widespread issue so I will update the tutorial and repository accordingly

**Comment by willwebberley** [comment] 2017-08-06 18:19
Hi all, many thanks for your feedback.

I am closing this issue now as both the tutorial and this demo repository have been updated to explain about configuring the AWS region before attempting the upload.

**Closed as completed by willwebberley** 2017-08-06 18:19 UTC
